### ISSUE TITLE
Add collapse all threads option

### ISSUE THREAD

**Issue by ulises** [Humbedooh/ponymail#2]
When multiple threads are unfolded, it's difficult to find unfolded threads.

**Comment by Humbedooh** [comment]
Two x escape key now closes all threads (one escape key closes the current, second one closes the rest). This should probably be written in some help popup somewhere, but for now, I'll consider this done.

**Comment by ulises** [comment]
Great to have the functionality, but I'd be wary of undocumented keybindings. Can we have a clickity buttony thing? Or does that not make sense?

I suspect that the answer is: it depends. It depends on whether we want power users, or whether all users are power users, etc.

**Comment by Humbedooh** [comment]
Also depends on the "TOO MANY BUTTONS" nightmare we could face at some point. I'd really love some input from some UI folks with more insight into how one does that :)

**Comment by ulises** [comment]
Yes, too many buttons is bad, to few is also bad. And the question remains: power users or not?

Let's take gmail for example (I know, I know). You can basically do everything with buttons, but also with keybindings. That sort of approach would be ideal IMO.

For now I think this can remain closed since the functionality is there. We just need to unify the UI and tie it to the app features.
