### ISSUE TITLE
Add "clear filters" option

### ISSUE THREAD

**Issue by ulises** [Humbedooh/ponymail#3]
I understand that going back a page would undo the last filter.

Ideally this should be more explicit, and it should clear all filters applied, not just the last.

**Comment by Humbedooh** [comment]
There is only ever one filter applied to a search, which is the current filter.
Going back applies the old filter, going forward applies the newer one, but not on the data filtered by the old filter. So I don't quite see the issue here.

**Comment by ulises** [comment]
Going back to undo the filter is not documented (granted, nothing is atm). I'd personally find it easier to use if there was a way to undo filtering right on the screen.

As mentioned in the ponymail thread: the behaviour is a mixture of webpage apps with webapps (the distinction being that some operations are done via clickity buttons and others via browser operations, e.g. navigating back). Some unification here would be good.

**Comment by Humbedooh** [comment]
Does 928d593 address your concerns?

**Comment by ulises** [comment]
does fix!

**Comment by Humbedooh** [comment]
closing as fixed then!
