### ISSUE TITLE
Cannot login by OAuth

### ISSUE THREAD

**Issue by tisonkun** [Humbedooh/ponymail#551]
I'm trying to login from the website UI and successfully sign in with my Apache account (`tison`). However, when I jump back to the original page I'm still in state no login.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/18818196/157024247-c22037fb-22f2-497d-aaaf-5277658d4462.png">

**Comment by tisonkun** [comment]
UPDATE: it happens only in Chrome and when I use Incognito mode, the problem vanished.

**Comment by sebbASF** [comment]
That suggests that it is a cookie issue. Clear all the relevant cookies and try again
