### ISSUE TITLE
Permalink should open in new window

### ISSUE THREAD

**Issue by ulises** [Humbedooh/ponymail#7]

**Comment by Humbedooh** [comment]
I don't consider this a bug, but rather an opinion on how the UI should work. I think we should solicit input from more people on this matter, as I know a lot of people have the exact opposite view; That links should NOT open in a new tab by default.

**Comment by Humbedooh** [comment]
Permalinks are now actual links. Users can choose to open them in a new window/tab (middle-click?)  or open them in the same window. Does this work for you?

**Comment by ulises** [comment]
Works just fine for me.

**Comment by Humbedooh** [comment]
Closing as resolved then.
also, ponies!
