### ISSUE TITLE
Message wrap broken in Firefox

### ISSUE THREAD

**Issue by ulises** [Humbedooh/ponymail#8]
From the ML:
"Message lines that are too long are truncated in Firefox. There is a slider, but that only appears when the message is selected, so it looks like text is missing. If wrapping doesn't work on Firefox, it might be better to always display the slider if it is going to be needed; that would act as an indication that the message has more data."

**Comment by Humbedooh** [comment]
I don't see where this issue is present. Could you give me a link?

**Comment by ulises** [comment]
Not I personally. I simply moved this issue from a ponymail thread. Feel free to close if can't reproduce.

**Comment by Humbedooh** [comment]
I think it was actually fixed a while back on the dev/bug list. Closing as fixed for now at least
