### ISSUE TITLE
Button thread is at the bottom of the page

### ISSUE THREAD

**Issue by ulises** [Humbedooh/ponymail#9]
From the ML: "The new thread button is at the bottom of the screen and can be hard to find if there are lots of threads open. Might be good to have another button in the menu line."

Additionally, the "Next..." button is also at the bottom of the page. It should also be at the top.

**Comment by Humbedooh** [comment]
Yeah, we need to add a "tools" menu item to the top with the stuff we'd otherwise have 28748 buttons for. I'll look into that ASAP.

**Comment by Humbedooh** [comment]
All done and fixed for now :)
We have buttons both top + bottom now, and the 'start discussion' option in the menu with logged in.
